project:
  type: website
  output-dir: docs

header-includes:
  - \usepackage{soul}
latex-clean: true

books:
  - book:
    downloads: [pdf]
    title: "Aligning business processes with regulatory requirements"
    subtitle: "Selected abstracts"
    pdf-url: https://jan-ru.github.io/yr2_abstracts/abstracts/yr2_abstracts.pdf
    date: last-modified
    date-format: "DD/MM/YYYY"
    chapters:
      - index.qmd
      - text: Aa2017
        file: abstracts/Aa2017.md
      - text: Amantea2022
        file: abstracts/Amantea2022.md
      - text: Bernardojunior2023
        file: abstracts/Bernardojunior2023.md
      - text: Bevilacqua2012
        file: abstracts/Bevilacqua2012.md
      - text: Corsius2021
        file: abstracts/Corsius2021.md
      - text: Elgammal2014
        file: abstracts/Elgammal2014.md
      - text: Hadasch2016
        file: abstracts/Hadasch2016.md
      - text: Hashmi2017
        file: abstracts/Hashmi2017.md
      - text: Hashmi2018
        file: abstracts/Hashmi2018.md
      - text: Holzmüller-Laue2014
        file: abstracts/Holzmüller-Laue2014.md
      - text: Kir2021
        file: abstracts/Kir2021.md
      - text: Koncevics2017
        file: abstracts/Koncevics2017.md
      - text: Lohmann2013
        file: abstracts/Lohmann2013.md
      - text: Loreti2018
        file: abstracts/Loreti2018.md
      - text: Mendling2018
        file: abstracts/Mendling2018.md
      - text: Ramezani2011
        file: abstracts/Ramezani2011.md
      - text: Raucci2020
        file: abstracts/Raucci2020.md
      - text: Sackmann2018
        file: abstracts/Sackmann2018.md
      - text: Vanderaalst2018
        file: abstracts/Vanderaalst2018.md
      - text: Vanderfeesten2011
        file: abstracts/Vanderfeesten2011.md
      - text: Viriyasitavat2020
        file: abstracts/Viriyasitavat2020.md
      - text: Viriyasitavat2023
        file: abstracts/Viriyasitavat2023.md
      - text: Zasada2023
        file: abstracts/Zasada2023.md


bibliography: bib/MyLibrary.bib
reference-location: section
link-citations: true

metadata-files:
  - ./metadata/_website.yml
  - ./metadata/_format.yml

execute:
  echo: false
  freeze: auto
