# Definitions

[
The term ‘compliance’ is generally used in a very broad sense denoting the adherence to source rules (developed to apply to participants and on their behaviour in some local contexts) to the target rules (developed for a wider community of participants in a potentially global context). Essentially, target rules such as norms, laws, regulations, recommendations etc., prescribe some requirements or expectations—and if acted upon, generate some effects or value to their subjects. Adherence of source rules to the target rules guarantees that prescribed requirements or expectations can be met (Governatori and Sadiq, 2009). From a business process compliance perspective, compliance aims to ensure that organisations’ operations, business processes and practices are in alignment with a prescribed set of regulatory laws. 

McIntyre (2008) defines compliance as:  “A desired outcome, with regard to law and regulations, internal policies and procedures, and commitments to stakeholders that can be consistently achieved through a managed investment of time and resources. The compliance management includes the legal and tactical activities in day–to–day business processes.”  

In contrast, Governatori (2005) views compliance as:  “an act/process to ensure that business operations, processes, and practices are in accordance with prescriptive (often legal) documents.”

  {
    "ID": 6,
    "Concept": "Compliance",
    "Definition": "a term generally used to refer to the conformance to a set of laws, regulations, internal policies, SLA, standards, or best practices (compliance sources according to COMPAS conceptual model [D7.1]).”,
    "Source(s) : "([pdf](zotero://open-pdf/library/items/F9DC3ASQ?page=6&annotation=88RIKA78))",
    "Date Accessed": "2024-06-09",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 7,
    "Concept": "Compliance Management",
    "Definition": "”, 
    "Source(s) : "",
    "Date Accessed": "",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 8,
    "Concept": "Compliance Management Framework",
    "Definition": "Compliance governance refers to the set of procedures, methodologies, and technologies put in place by a corporation to carry out, monitor, and manage compliance.”, 
    "Source(s) : "([pdf](zotero://open-pdf/library/items/F9DC3ASQ?page=6&annotation=3QZXX5ZL))", "Hashmi2017",
    "Date Accessed": "2024-06-09",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 9,
    "Concept": "Formal Methods",
    "Definition": "”, 
    "Source(s) : "",
    "Date Accessed": "",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 9,
    "Concept": "Regulatory Compliance",
    "Definition": "”, 
    "Source(s) : "",
    "Date Accessed": "",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 10,
    "Concept": "Smart Contracts",
    "Definition": "”, 
    "Source(s) : "",
    "Date Accessed": "",
    "Notes": "Additional comments or contextual information"
  }
  {
    "ID": 11,
    "Concept": "Workflow Management",
    "Definition": "”, 
    "Source(s) : "",
    "Date Accessed": "",
    "Notes": "Additional comments or contextual information"
  }
]