flowchart TB
  %%{init: {'theme':'neutral'}}%%
  A("Identify &
  Define")
  B("Track & 
  Analyze")
  C("Monitor & 
  Map")
  D("Control & 
  Manage")
  E("Report & 
  Record")
  A --> B
  B --> C
  C --> D
  D --> E